version: 2.1

jobs:
  build_doc:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - run:
          name: Complete checkout
          command: |
            if ! git remote -v | grep upstream; then
              git remote add upstream https://github.com/py-why/dodiscover.git
            fi
            git remote set-url upstream https://github.com/py-why/dodiscover.git
            git fetch upstream
      - save_cache:
          name: Save .git
          key: source-cache-graphs
          paths:
            - ".git"
      - run:
          name: Check-skip
          command: |
            set -e
            export COMMIT_MESSAGE=$(git log --format=oneline -n 1);
            if [[ -v CIRCLE_PULL_REQUEST ]] && ([[ "$COMMIT_MESSAGE" == *"[skip circle]"* ]] || [[ "$COMMIT_MESSAGE" == *"[circle skip]"* ]]); then
              echo "Skip detected, exiting job ${CIRCLE_JOB} for PR ${CIRCLE_PULL_REQUEST}."
              circleci-agent step halt;
            fi
      - restore_cache:
          keys:
            - poetry-v1-{{ checksum "poetry.lock" }}
            - poetry-v1-

      - run:
          name: Set BASH_ENV
          command: |
            set -e
            sudo apt update
            sudo apt-get update
            sudo apt install -qq graphviz optipng libxft2 graphviz-dev
            echo 'set -e' >> $BASH_ENV
            echo 'export OPENBLAS_NUM_THREADS=4' >> $BASH_ENV
            echo 'export XDG_RUNTIME_DIR=/tmp/runtime-circleci' >> $BASH_ENV
            echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV
            echo 'export DISPLAY=:99' >> $BASH_ENV
            echo 'BASH_ENV:'
            cat $BASH_ENV
      - run:
          name: Install pysal dependencies
          command: |
            sudo apt install libspatialindex-dev xdg-utils shared-mime-info

      - run:
          name: Setup pandoc
          command: sudo apt update && sudo apt install -y pandoc optipng

      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python -
            export PATH='$HOME/.poetry/bin:$PATH'

      - run:
          name: Install Dependencies
          command: |
            poetry install --no-interaction --no-ansi  --with docs --extras viz --extras graph_func

      - run:
          name: Show installed versions
          command: |
            poetry show

      - save_cache:
          paths:
            - $HOME/.poetry
          key: poetry-v1-{{ checksum "poetry.lock" }}

      - run:
          name: Build Documentation
          command: |
            poetry run poe build_docs
      # Save the example test results
      - store_test_results:
          path: doc/_build/test-results
      - store_artifacts:
          path: doc/_build/test-results
          destination: test-results
      # Save the SG RST
      - store_artifacts:
          path: doc/auto_examples.zip
      - store_artifacts:
          path: doc/generated.zip
      # Save the outputs
      - store_artifacts:
          path: doc/_build/html/
          destination: dev
      - store_artifacts:
          path: doc/_build/html_stable/
          destination: stable
      - persist_to_workspace:
          root: doc/_build
          paths:
            - html
            - html_stable

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - attach_workspace:
          at: doc/_build
      - run:
          name: Set BASH_ENV
          command: |
            set -e
            echo "set -e" >> $BASH_ENV
      # Don't try to deploy if nothing is there or not on the right branch
      - run:
          name: Check docs
          command: |
            if [ ! -f doc/_build/html/index.html ] && [ ! -f doc/_build/html_stable/index.html ]; then
              echo "No files found to upload (build: ${CIRCLE_BRANCH}).";
              circleci-agent step halt;
            fi;
      - run:
          name: Install and configure dependencies
          # do not update gh-pages above 3.0.0
          # see: https://github.com/tschaub/gh-pages/issues/354
          command: |
            npm install gh-pages@3.0
            git config --global user.email "circle@pywhy.com"
            git config --global user.name "Circle Ci"
      - add_ssh_keys:
          fingerprints:
            - "2d:4e:14:8e:32:00:68:e5:f9:dd:64:17:07:3e:2c:9e"
      - run:
          # push built doc into the `dev` directory on the `gh-pages` branch
          name: Deploy doc to gh-pages branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "Deploying dev doc for ${CIRCLE_BRANCH}.";
              node_modules/gh-pages/bin/gh-pages.js --dotfiles --message "doc updates [skip ci]" --dist doc/_build/html --dest ./dev
            else
              echo "Deploying stable doc for ${CIRCLE_BRANCH}.";
              node_modules/gh-pages/bin/gh-pages.js --dotfiles --message "doc updates [skip ci]" --dist doc/_build/html_stable --dest ./stable
            fi;

workflows:
  default:
    jobs:
      - build_doc:
          name: build_doc
      - deploy:
          requires:
            - build_doc
          filters:
            branches:
              only:
                - main

  main:
    jobs:
      - build_doc:
          name: build_doc_main
      - deploy:
          name: deploy_main
          requires:
            - build_doc_main
    triggers:
      - schedule:
          # "At 00:00" (once a day) should be enough "0 0 * * *",
          # But for testing at first, let's do once an hour (6 AM GMT)
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
